version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/utn_tailwind_theme/static_src"
    schedule:
      interval: "daily"
