# Generated by Django 3.1.7 on 2021-03-12 13:23

import bocken.fields
import bocken.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Agreement number')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('personnummer', models.CharField(max_length=13, unique=True, validators=[bocken.validators.validate_personnummer])),
                ('phonenumber', bocken.fields.PhonenumberField(max_length=20, validators=[bocken.validators.validate_phonenumber], verbose_name='Phonenumber')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('expires', models.DateField(verbose_name='Valid until')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost_per_mil', models.PositiveIntegerField(default=20)),
                ('starting_fee', models.PositiveIntegerField(default=0)),
                ('main_group', models.CharField(choices=[('committees_workgroups', "UTN's committees and workgroups"), ('lg_and_board', "UTN's management team and board"), ('fum', 'FUM'), ('other_officials', 'Other officials within UTN'), ('sections', 'Sections'), ('cooperations', 'Cooperations')], max_length=30, verbose_name='Main group')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.DateTimeField()),
                ('last', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_start', models.PositiveIntegerField(verbose_name='Meter at start')),
                ('meter_stop', models.PositiveIntegerField(verbose_name='Meter at stop')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bocken.agreement', verbose_name='Agreement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bocken.journalentrygroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'get_latest_by': 'created',
            },
        ),
    ]
