# Generated by Django 3.1.5 on 2021-02-02 13:28

import bocken.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=120)),
                ('personnummer', models.TextField(max_length=13, validators=[bocken.validators.validate_personnummer])),
                ('phonenumber', models.TextField(max_length=20, validators=[bocken.validators.validate_phonenumber])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('signed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('group', models.TextField(choices=[])),
                ('meter_start', models.IntegerField()),
                ('meter_stop', models.IntegerField()),
                ('total_distance', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agreement_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bocken.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bocken.journalentry')),
                ('last', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bocken.journalentry')),
            ],
        ),
    ]
