# Generated by Django 3.1.7 on 2021-03-12 12:55

from django.db import migrations

committees_and_workgroups = [
    {'name': 'Baskå', },
    {'name': 'TD', },
    {'name': 'Proppen', },
    {'name': 'KV', },
    {'name': 'Rallykå', },
    {'name': 'Balkå', },
    {'name': 'Cafegruppen', },
    {'name': 'Forskå', },
    {'name': 'Eventgruppen', },
    {'name': 'Examenkå', },
    {'name': 'Marknadsföringsgruppen', },
    {'name': 'MER', },
    {'name': 'Utnarm', },
    {'name': 'Polhackskå', },
    {'name': 'Dkå', },
    {'name': 'Kårhusgruppen', },
    {'name': 'Techna', },
]

lg_and_board = [
    {'name': 'Utb-ex', },
    {'name': 'Utb-n', },
    {'name': 'Utb-t', },
    {'name': 'Soc', },
    {'name': 'Int', },
    {'name': 'NA', },
    {'name': 'PL Utnarm', },
    {'name': 'Ordförande', },
    {'name': 'Vice Ordförande', },
    {'name': 'Styrelsen', },
]

fum = [
    {'name': 'TMP', },
    {'name': 'Valberedningen', },
]

other_officials = [
    {'name': 'Förvaltning', },
    {'name': 'Historiograf', },
    {'name': 'Pelarmarskalk', },
    {'name': 'Internrevisorer', },
]

sections = [
    {'name': 'BAS', },
    {'name': 'DV', },
    {'name': 'E', },
    {'name': 'ES', },
    {'name': 'F', },
    {'name': 'H', },
    {'name': 'I', },
    {'name': 'IT', },
    {'name': 'K', },
    {'name': 'NVB (BÄR)', },
    {'name': 'NVF (FysKam)', },
    {'name': 'NVG (GRUS)', },
    {'name': 'NVK (IUPAK)', },
    {'name': 'NVL (LärNat)', },
    {'name': 'NVM (Moebius)', },
    {'name': 'Q', },
    {'name': 'STS', },
    {'name': 'W', },
    {'name': 'X', },
]

cooperations = [
    {'name': 'BEST', },
    {'name': 'Teknat Spex', },
    {'name': 'Genius', },
    {'name': 'IAESTE', },
    {'name': 'IBK', },
    {'name': 'IGEM', },
    {'name': 'SIV', },
    {'name': 'MFK', },
    {'name': 'GB', },
]

all_groups = {
    'committees_workgroups': committees_and_workgroups,
    'lg_and_board': lg_and_board,
    'fum': fum,
    'other_officials': other_officials,
    'sections': sections,
    'cooperations': cooperations,
}


def add_default_groups(apps, schema_editor):
    """Add the groups that are most likely to use bocken."""
    model = apps.get_model("bocken", "JournalEntryGroup")
    for main_group, groups in all_groups.items():
        for group in groups:
            created_group = model.objects.create(
                name=group['name'],
                main_group=main_group
            )

            if main_group == 'sections':
                created_group.starting_fee = 150
                created_group.save()


def remove_default_groups(apps, schema_editor):
    """Remove the groups in case a rollback is needed."""
    model = apps.get_model("bocken", "JournalEntryGroup")
    for main_group, groups in all_groups.items():
        for group in groups:
            model.objects.get(name=group['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_groups, remove_default_groups)
    ]
