# Generated by Django 3.1.7 on 2021-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0002_auto_20210312_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentrygroup',
            options={'verbose_name': 'Journal entry group', 'verbose_name_plural': 'Journal entry groups'},
        ),
        migrations.RemoveField(
            model_name='journalentrygroup',
            name='starting_fee',
        ),
        migrations.AlterField(
            model_name='journalentrygroup',
            name='cost_per_mil',
            field=models.PositiveIntegerField(default=20, verbose_name='Cost per mil'),
        ),
        migrations.AlterField(
            model_name='journalentrygroup',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
    ]
