# Generated by Django 4.0.3 on 2022-03-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0002_default_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'get_latest_by': 'meter_stop', 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
    ]
