# Generated by Django 3.1.5 on 2021-02-05 13:20

import bocken.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0002_auto_20210203_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='agreement_number',
            new_name='agreement',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='personnummer',
            field=models.TextField(max_length=13, unique=True, validators=[bocken.validators.validate_personnummer]),
        ),
    ]
