# Generated by Django 3.1.7 on 2021-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0003_auto_20210316_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_mil', models.PositiveIntegerField(default=20, verbose_name='Cost per mil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
