# Generated by Django 4.1.4 on 2022-12-15 16:24

from django.db import migrations


def personnummer_is_t_number(personnummer):
    """Check if the given personnummer is a t-number."""
    # If the first digit in the 4 last digits in a personnummer is
    # one of the following letters, the personnummer is a t-number.
    # These letters are the only ones that are allowed in a t-number.
    if len(personnummer) < 10 or len(personnummer) > 14:
        return False

    return personnummer[-4].upper() in [
        'T', 'R', 'S', 'U', 'W', 'X',
        'J', 'K', 'L', 'M', 'N'
    ]


def alter_t_numbers(apps, schema_editor):
    # We can't import the Agreement model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    agreement_model = apps.get_model('bocken', 'Agreement')
    for agreement in agreement_model.objects.all():
        if personnummer_is_t_number(agreement.personnummer):
            agreement.personnummer = agreement.personnummer.replace("-", "")
            agreement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0003_alter_journalentry_options'),
    ]

    operations = [
        migrations.RunPython(alter_t_numbers),
    ]
