# Generated by Django 3.1.5 on 2021-02-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0003_auto_20210205_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='name',
        ),
    ]
