# Generated by Django 3.1.7 on 2021-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.RemoveField(
            model_name='journalentrygroup',
            name='cost_per_mil',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cost_per_mil',
            field=models.PositiveIntegerField(default=20, verbose_name='Cost per mil (kr)'),
        ),
    ]
