# Generated by Django 4.2.1 on 2024-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0004_alter_t_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_bocken_type',
            field=models.BooleanField(default=False, verbose_name='Agreement for bocken'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement_hornet_type',
            field=models.BooleanField(default=False, verbose_name='Agreement for hornet'),
        ),
    ]
