# Generated by Django 3.1.5 on 2021-02-05 15:01

import bocken.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0004_remove_journalentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='personnummer',
            field=models.CharField(max_length=13, unique=True, validators=[bocken.validators.validate_personnummer]),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='phonenumber',
            field=models.CharField(max_length=20, validators=[bocken.validators.validate_phonenumber]),
        ),
    ]
