# Generated by Django 4.2.1 on 2024-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0004_alter_t_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='bike_agreement',
            field=models.BooleanField(default=False, help_text='Designates whether user has a agreement which applies for bikes or not.', verbose_name='Agreement for bikes'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='car_agreement',
            field=models.BooleanField(default=False, help_text='Designates whether user has a agreement which applies for cars or not.', verbose_name='Agreement for cars'),
        )
    ]
