# Generated by Django 4.2.1 on 2024-06-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0005_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bocken.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_meter_start',
            field=models.PositiveIntegerField(default=0, verbose_name='Meter at start (Latest Entry)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_meter_stop',
            field=models.PositiveIntegerField(default=0, verbose_name='Meter at stop (Latest Entry)'),
        ),
    ]
