# Generated by Django 4.2.1 on 2024-06-26 11:29

from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist
import django.db.models.deletion

all_vehicles = [
    # Bocken last values as per 26/06/24: 37684	37697
    {"vehicle_name" : "Bocken", "car": True, "bike": False, "vehicle_meter_start": 37684, "vehicle_meter_stop": 37697},
    {"vehicle_name" : "Bjällran", "car": False, "bike": True,  "vehicle_meter_start": 0, "vehicle_meter_stop": 0}
]

def add_default_vehicles(apps, schema_editor):
    model = apps.get_model("bocken", "Vehicle")
    for vehicle in all_vehicles:
            created_vehicle = model.objects.create(
                vehicle_name=vehicle['vehicle_name'],
                vehicle_meter_start = vehicle['vehicle_meter_start'],
                vehicle_meter_stop = vehicle['vehicle_meter_stop'],
                car = vehicle['car'],
                bike = vehicle['bike'],
            )


def remove_default_vehicles(apps, schema_editor):
    model = apps.get_model("bocken", "Vehicle")
    for vehicle in all_vehicles:
        try:
            vehicle_to_delete = model.objects.get(vehicle_name=vehicle['vehicle_name']).delete()
        except ObjectDoesNotExist:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0005_add_agreement_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=60, verbose_name='Name')),
                ('car',models.BooleanField(default=False,verbose_name='Is the vehicle a car')),
                ('bike',models.BooleanField(default=False,verbose_name='Is the vehicle a bike')),
                ('vehicle_meter_start',models.PositiveIntegerField(default=0,verbose_name='Meter at start (Latest Entry)')),
                ('vehicle_meter_stop',models.PositiveIntegerField(default=0,verbose_name='Meter at stop (Latest Entry)')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='vehicle',
            # default here ensures all old entries are set to bocken :)
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bocken.vehicle', verbose_name='Vehicle'),
        ),
        migrations.RunPython(add_default_vehicles, remove_default_vehicles)
    ]
