# Generated by Django 4.2.1 on 2026-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0006_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='bike_agreement',
            field=models.BooleanField(default=False, help_text='Designates whether user has a agreement which applies for bikes or not.', verbose_name='Agreement for bikes'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='car_agreement',
            field=models.BooleanField(default=False, help_text='Designates whether user has a agreement which applies for cars or not.', verbose_name='Agreement for cars'),
        ),
    ]
