# Generated by Django 3.1.5 on 2021-02-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0006_auto_20210205_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='group',
            field=models.CharField(max_length=120),
        ),
    ]
