# Generated by Django 3.2 on 2021-04-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0007_auto_20210419_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='number',
            new_name='id',
        ),
    ]
