# Generated by Django 3.2 on 2021-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0008_rename_number_agreement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
