# Generated by Django 3.2 on 2021-04-21 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0009_alter_agreement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=datetime.date(2022, 4, 21), verbose_name='Valid until'),
        ),
    ]
