# Generated by Django 3.2 on 2021-04-21 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0010_alter_agreement_expires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ('name',), 'verbose_name': 'Agreement', 'verbose_name_plural': 'Agreements'},
        ),
        migrations.AlterField(
            model_name='agreement',
            name='email',
            field=models.EmailField(blank=True, help_text="The person's private email. Should not be an email ending in @utn.se.", max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=datetime.date(2022, 4, 21), help_text='Agreements are valid for 1 year by default.', verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='name',
            field=models.CharField(help_text='First and last name', max_length=120, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['name', 'personnummer'], name='bocken_agre_name_39a69c_idx'),
        ),
    ]
