# Generated by Django 3.2 on 2021-04-22 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0011_auto_20210421_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=datetime.date(2022, 4, 22), help_text='Agreements are valid for 1 year by default.', verbose_name='Valid until'),
        ),
    ]
