# Generated by Django 3.1.5 on 2021-03-01 10:23

import bocken.fields
import bocken.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0012_auto_20210217_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Agreement', 'verbose_name_plural': 'Agreements'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Agreement number'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='phonenumber',
            field=bocken.fields.PhonenumberField(max_length=20, validators=[bocken.validators.validate_phonenumber], verbose_name='Phonenumber'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bocken.agreement', verbose_name='Agreement'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='group',
            field=models.CharField(choices=[('baska', 'Baskå'), ('td', 'TD'), ('proppen', 'Proppen'), ('kv', 'KV'), ('rebusrallyt', 'Rallykå'), ('balen', 'Balkå'), ('cafegruppen', 'Cafegruppen'), ('forska', 'Forskå'), ('eventgruppen', 'Eventgruppen'), ('exka', 'Examenkå'), ('marknadsforingsgruppen', 'Marknadsföringsgruppen'), ('mer', 'MER'), ('utnarm', 'Utnarm'), ('polhacks', 'Polhackskå'), ('dka', 'Dkå'), ('karhusgruppen', 'Kårhusgruppen'), ('techna', 'Techna'), ('best', 'BEST'), ('teknatspex', 'Teknat Spex'), ('genius', 'Genius'), ('iaeste', 'IAESTE'), ('ibk', 'IBK'), ('igem', 'IGEM'), ('siv', 'SIV'), ('mfk', 'MFK'), ('gb', 'GB'), ('tmp', 'TMP'), ('valberedningen', 'Valberedningen'), ('board', 'Styrelsen'), ('utbex', 'Utb-ex'), ('utbn', 'Utb-n'), ('utbt', 'Utb-t'), ('soc', 'Soc'), ('int', 'Int'), ('na', 'NA'), ('plutnarm', 'PL Utnarm'), ('ordf', 'Ordförande'), ('viceordf', 'Vice Ordförande'), ('forvaltning', 'Förvaltning'), ('historiograf', 'Historiograf'), ('pelarmarskalk', 'Pelarmarskalk'), ('internrevisorer', 'Internrevisorer'), ('bas', 'BAS'), ('dv', 'DV'), ('e', 'E'), ('es', 'ES'), ('f', 'F'), ('h', 'H'), ('i', 'I'), ('it', 'IT'), ('k', 'K'), ('nvb', 'NVB (BÄR)'), ('nvf', 'NVF (FysKam)'), ('nvg', 'NVG (GRUS)'), ('nvk', 'NVK (IUPAK)'), ('nvl', 'NVL (LärNat)'), ('nvm', 'NVM (Moebius)'), ('q', 'Q'), ('sts', 'STS'), ('w', 'W'), ('x', 'X')], max_length=120, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='meter_start',
            field=models.PositiveIntegerField(verbose_name='Meter at start'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='meter_stop',
            field=models.PositiveIntegerField(verbose_name='Meter at stop'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='total_distance',
            field=models.PositiveIntegerField(verbose_name='Driven Distance (km)'),
        ),
    ]
