# Generated by Django 3.1.5 on 2021-02-24 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0012_auto_20210217_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
