# Generated by Django 3.2 on 2021-04-23 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0012_auto_20210422_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=datetime.date(2022, 4, 23), help_text='Agreements are valid for 1 year by default.', verbose_name='Valid until'),
        ),
    ]
