# Generated by Django 3.2 on 2021-05-03 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0013_auto_20210423_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='email',
            field=models.EmailField(
                help_text="The person's private email. Should not be an email ending in @utn.se.", max_length=254, null=True, unique=True),
        )
    ]
