# Generated by Django 3.1.7 on 2021-03-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0013_auto_20210301_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'get_latest_by': 'created', 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'created', 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='total_distance',
        ),
    ]
