# Generated by Django 3.2 on 2021-04-27 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0013_auto_20210423_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=datetime.date(2022, 4, 27), help_text='Agreements are valid for 1 year by default.', verbose_name='Valid until'),
        ),
    ]
