# Generated by Django 3.1.7 on 2021-03-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0014_auto_20210310_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='first',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last',
        ),
    ]
