# Generated by Django 3.2.3 on 2021-05-19 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0014_alter_agreement_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_file',
            field=models.FileField(blank=True, upload_to='agreements/', verbose_name='Signed agreement'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=datetime.date(2022, 5, 19), help_text='Agreements are valid for 1 year by default.', verbose_name='Valid until'),
        ),
    ]
