# Generated by Django 3.2.3 on 2021-05-19 08:43

import bocken.models.agreement
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0014_alter_agreement_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='expires',
            field=models.DateField(default=bocken.models.agreement.get_default_expires, help_text='Agreements are valid for 1 year by default.', verbose_name='Valid until'),
        ),
    ]
