# Generated by Django 3.2.3 on 2021-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0015_auto_20210519_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="The person's private email. Should not be an email ending in @utn.se.", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
