# Generated by Django 3.1.7 on 2021-03-11 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0015_auto_20210311_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='last',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 8, 30, 29, 339122, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
