# Generated by Django 3.2 on 2021-05-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0015_alter_agreement_expires'),
        ('bocken', '0016_alter_agreement_email'),
    ]

    operations = [
    ]
