# Generated by Django 3.2.3 on 2021-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocken', '0017_merge_20210519_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='email',
            field=models.EmailField(blank=True, help_text="The person's private email. Should not be an email ending in @utn.se.", max_length=254),
        ),
    ]
